# Generated by Django 3.2.7 on 2021-11-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_rank_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_genre', models.IntegerField(choices=[('1', '공포'), ('2', '행복'), ('3', '놀람')])),
            ],
        ),
    ]
