# Generated by Django 3.2.7 on 2021-11-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_selectgenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectgenre',
            name='selected_genre',
            field=models.IntegerField(choices=[('12', '모험'), ('14', '판타지'), ('16', '애니메이션'), ('18', '드라마'), ('27', '공포'), ('28', '액션'), ('35', '코미디'), ('36', '역사'), ('37', '서부'), ('53', '스릴러'), ('80', '범죄'), ('99', '다큐멘터리'), ('878', 'SF'), ('9648', '미스터리'), ('10402', '음악'), ('10749', '로맨스'), ('10751', '가족'), ('10752', '전쟁'), ('10770', 'TV 영화')]),
        ),
    ]
