# Generated by Django 3.2.9 on 2021-11-23 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_review_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
    ]
