# Generated by Django 3.2.6 on 2021-11-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_rank_user'),
        ('accounts', '0003_remove_user_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genres',
            field=models.ManyToManyField(to='movies.Genre'),
        ),
    ]
